title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- .github
- scripts
- vendor
- logs
- assets
- .github
- data
ext:
- go
- js
- tmpl
- ini
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - rm -rf logs/run_away.log
  - gofmt -w ./
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go

  after:
  - ps -ef|grep 'imail service'| grep -v grep | awk '{print $2}' | xargs kill -9 
  -  ./imail service &
  exit:
  - ps -ef|grep 'imail service'| grep -v grep
  - ps -ef|grep 'imail service'| grep -v grep | awk '{print $2}' | xargs kill -9
  - rm -rf ./imail